### ISSUE TITLE
How can I apply this model to "document classification" or "image recognition task from MNIST" problem?

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [thaihungle/UW-DNC#1]
Your marvellous work greatly inspires me, and I would like to establish a similar model for  "document classification" or "image recognition task from MNIST" problem as your paper mentions. For this purpose, how should I modify the source codes?

**Comment by thaihungle** [comment]
Thank you for your interest in my work. You can find an example of running synthetic tasks in synthetic_task.py and running the nlp tasks is similar. You should prepare the nlp data input in the same format as in the synthetic tasks (i.e, tensor of shape [batch_size, sequence_length, input_dimension]). You can find the loss function and output for the nlp tasks in uw_dnc.py: build_loss_function_multi_label. Other details are mentioned in the paper.

**Comment by jx-zhong-for-academic-purpose** [comment]
OK. Thanks.
